version: '3.8'

services:
  nginx:
    container_name: nginx
    build:
      dockerfile: Dockerfile_nginx
    ports:
      - "8084:80"
    volumes:
      - ./nginx.conf:/etc/nginx.conf.d
      - .:/app
      - ./static:/static
    depends_on:
      - django_app

  django_app:
    container_name: django_app
    image: hy_act_server_django_app
    build:
      context: .
    command: gunicorn hy_act_server.wsgi:application --bind 0.0.0.0:8000
    expose:
      - "8000"
    restart: always
    volumes:
      - .:/app
    depends_on:
      - migration

  migration:
    image: hy_act_server_django_app
    command: python manage.py migrate --noinput
    volumes:
      - .:/app

networks:
  app-tier:
    driver: bridge