version: '3'
services:
  hy-act-server:
      build: ./server
      ports:
        - 8000:8080
      volumes:
        - /etc/localtime:/etc/localtime:ro
  hy-act-client:
      build: ./client
      ports:
        - 9000:9000
      depends_on:
        - hy-act-server
      volumes:
        - /etc/localtime:/etc/localtime:ro