# Generated by Django 4.0.4 on 2022-05-21 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_alter_program_options_program_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='class_end_at',
            new_name='program_end_at',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='class_start_at',
            new_name='program_start_at',
        ),
    ]
