# Generated by Django 4.0.4 on 2022-06-10 14:55

from django.db import migrations, models
import django.db.models.deletion
import program.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_departments_alter_user_majors'),
        ('program', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancecode',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'start'), (1, 'end')], default=0),
        ),
        migrations.AlterField(
            model_name='attendancecode',
            name='code',
            field=models.CharField(default=program.models.generate_digit_code, max_length=200),
        ),
        migrations.AlterField(
            model_name='attendancecode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attendancecode',
            name='expire_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.department'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
