# Generated by Django 4.0.4 on 2022-06-15 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('program', '0006_program_lecturer_alter_program_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructing_program_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='program',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='managing_program_set', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
