# Generated by Django 4.0.4 on 2022-06-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_department_major_alter_user_telephone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='departments',
            field=models.ManyToManyField(blank=True, to='user.department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='majors',
            field=models.ManyToManyField(blank=True, to='user.major'),
        ),
    ]
