# Generated by Django 4.0.4 on 2022-06-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_attendancecode_type_alter_attendancecode_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='attendance_end_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='attendance_start_at',
            field=models.DateTimeField(null=True),
        ),
    ]
